[package]
authors = ["tupl"]
categories = ["command-line-utilities"]
description = "GraphQL Object Reverse Lookup"
edition = "2024"
keywords = ["GraphQL"]
license = "GPL-3.0-or-later"
name = "revql"
readme = "README.md"
repository = "https://github.com/tupl-dev/revql"
version = "0.1.0"

[dependencies]
clap = { features = ["derive"], version = "4.6" }
colored = { version = "3.1" }
graphql-introspection-query = { version = "0.3" }
reqwest = { features = ["blocking", "json", "query"], version = "0.13" }
serde_json = { version = "1.0" }
thiserror = { version = "2.0" }

[dev-dependencies]
tempfile = { version = "3.27" }

[lints.clippy]
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

dbg_macro = "warn"
exit = "warn"
expect_used = "warn"
indexing_slicing = "warn"
missing_errors_doc = "allow"
multiple_crate_versions = "allow"
panic = "warn"
ref_patterns = "warn"
rest_pat_in_fully_bound_structs = "warn"
str_to_string = "warn"
string_slice = "warn"
todo = "warn"
try_err = "warn"
unchecked_time_subtraction = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
unreachable = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = "symbols"

[[test]]
name = "functional"
path = "tests/main.rs"
