name: CICD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v[0-9]+\.[0-9]+\.[0-9]+']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check Format
        run: cargo fmt --all --check --quiet
      - name: Check Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  test:
    name: Test
    needs: [analysis]
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Run Tests
        run: cargo test --all-features --all-targets

  prepare-release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Prepare Release
    needs: [test]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Create Release
        run: |
          gh release delete "${{ github.ref_name }}" --yes || true
          gh release create "${{ github.ref_name }}" --generate-notes --latest

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release
    needs: [prepare-release]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [
          { os: macos-latest, suffix: macos-arm64 },
          { os: ubuntu-latest, suffix: linux-amd64 },
          { os: windows-latest, suffix: windows-amd64.exe },
        ]

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Build and Upload
        shell: sh
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#v}"
          perl -pi -e "s/^version = .*/version = \"$VERSION\"/" Cargo.toml
          cargo install --path . --root release --force

          if [ -f "release/bin/revql.exe" ]; then
            mv "release/bin/revql.exe" "release/bin/revql-${{ matrix.platform.suffix }}"
          else
            mv "release/bin/revql" "release/bin/revql-${{ matrix.platform.suffix }}"
          fi
          gh release upload "${{ github.ref_name }}" release/bin/* --clobber
